name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate PDF
        run: |
          pdflatex -shell-escape -jobname=ctaps-thesis main.tex
          biber ctaps-thesis
          pdflatex -shell-escape -jobname=ctaps-thesis main.tex
          pdflatex -shell-escape -jobname=ctaps-thesis main.tex
      - uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          name: Latest build
          prerelease: true
          files: taps-for-linux.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
